development: &login
  adapter: mysql
  username: root
  password: mangos
  host: 192.168.1.155

mangos:
  <<: *login
  database: mangos

realmd:
  <<: *login
  database: realmd

characters:
  <<: *login
  database: characters

scriptdev2:
  <<: *login
  database: scriptdev2